{{- if .Values.secrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "app-stateful.fullname" . }}-secrets
spec:
  secretStoreRef:
    name: {{ .Values.secrets.secretStoreRef.name | quote }}
    kind: {{ .Values.secrets.secretStoreRef.kind | quote }}
  refreshInterval: {{ .Values.secrets.refreshInterval | quote }}
  target:
    creationPolicy: 'Owner'
    deletionPolicy: "Retain"
  dataFrom:
  - find:
      tags:
        {{ include "app-stateful.fullname" . }}: "true"
{{- range .Values.secrets.toFiles }}
  - find:
      name:
        regexp: {{ .name | quote }}
{{- end }}
{{- end }}
