{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "app-stateful.fullname" . }}-podDisruptionBudget
  annotations:
    {{- toYaml .Values.podDisruptionBudget.annotations | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "app-stateful.selectorLabels" . | nindent 6 }}
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if or .Values.podDisruptionBudget.maxUnavailable ( not .Values.podDisruptionBudget.minAvailable ) }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable | default 1 }}  
  {{- end }}
{{- end }}