{{- if .Values.autoscaling.redis.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "app.fullname" . }}-scaledobject
spec:
  scaleTargetRef:
    name:  {{ include "app.fullname" . }} 
  pollingInterval: {{ .Values.autoscaling.pollingInterval }}
  cooldownPeriod: {{ .Values.autoscaling.cooldownPeriod }}
  minReplicaCount: {{ .Values.autoscaling.minReplicaCount }}
  maxReplicaCount: {{ .Values.autoscaling.maxReplicaCount }}
  triggers:
  - type: redis
    metadata:
      address: {{ .Values.autoscaling.redis.address }}
      listName: {{ .Values.autoscaling.redis.listName  }}
      listLength: {{ .Values.autoscaling.redis.listLength | quote }}
      databaseIndex: {{ .Values.autoscaling.redis.databaseIndex | quote }}
{{- end }}

